# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.cache/wt [current_project]
set_property parent.project_path E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo e:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/new/BRAM_R_Init.coe
add_files E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/new/BRAM_G_Init.coe
add_files E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/new/BRAM_B_Init.coe
read_verilog -library xil_defaultlib {
  E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/BRAM_RGB/hdl/BRAM_RGB_wrapper.v
  E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/PLL/hdl/PLL_wrapper.v
  E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/new/data_out.v
  E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/new/lcd_pattern_generator.v
  E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/new/prescaler.v
  E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/new/test_lcd.v
  E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/new/top.v
  E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/HPS/hdl/HPS_wrapper.v
}
add_files E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/BRAM_RGB/BRAM_RGB.bd
set_property used_in_implementation false [get_files -all e:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/BRAM_RGB/ip/BRAM_RGB_blk_mem_gen_0_0/BRAM_RGB_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/BRAM_RGB/ip/BRAM_RGB_blk_mem_gen_R_0/BRAM_RGB_blk_mem_gen_R_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/BRAM_RGB/ip/BRAM_RGB_blk_mem_gen_R_1/BRAM_RGB_blk_mem_gen_R_1_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/BRAM_RGB/BRAM_RGB_ooc.xdc]

add_files E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/PLL/PLL.bd
set_property used_in_implementation false [get_files -all e:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/PLL/PLL_ooc.xdc]

add_files E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/HPS/HPS.bd
set_property used_in_implementation false [get_files -all e:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/HPS/ip/HPS_processing_system7_0_0/HPS_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/sources_1/bd/HPS/HPS_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/constrs_1/new/project_LCD.xdc
set_property used_in_implementation false [get_files E:/Xilinx/workspace/PYNQ_Z2/project_LCD_withZynq/project_LCD.srcs/constrs_1/new/project_LCD.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top HPS_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef HPS_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file HPS_wrapper_utilization_synth.rpt -pb HPS_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
