set_property SRC_FILE_INFO {cfile:E:/Xilinx/workspace/QM_Artix7DDR3CoreBoard/Test01_project_led/project_led.srcs/constrs_1/new/LED.xdc rfile:../../../project_led.srcs/constrs_1/new/LED.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E6 [get_ports led_1]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N11 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports sys_rst_n]
