# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/project_LCD.xdc

# Block Designs: bd/RGB_BRAM/RGB_BRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RGB_BRAM || ORIG_REF_NAME==RGB_BRAM} -quiet] -quiet

# IP: bd/RGB_BRAM/ip/RGB_BRAM_blk_mem_gen_0_0/RGB_BRAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RGB_BRAM_blk_mem_gen_0_0 || ORIG_REF_NAME==RGB_BRAM_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/RGB_BRAM/ip/RGB_BRAM_blk_mem_gen_R_0/RGB_BRAM_blk_mem_gen_R_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RGB_BRAM_blk_mem_gen_R_0 || ORIG_REF_NAME==RGB_BRAM_blk_mem_gen_R_0} -quiet] -quiet

# IP: bd/RGB_BRAM/ip/RGB_BRAM_blk_mem_gen_R1_0/RGB_BRAM_blk_mem_gen_R1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RGB_BRAM_blk_mem_gen_R1_0 || ORIG_REF_NAME==RGB_BRAM_blk_mem_gen_R1_0} -quiet] -quiet

# Block Designs: bd/design_PLL/design_PLL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_PLL || ORIG_REF_NAME==design_PLL} -quiet] -quiet

# IP: bd/design_PLL/ip/design_PLL_clk_wiz_0_0/design_PLL_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_PLL_clk_wiz_0_0 || ORIG_REF_NAME==design_PLL_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/RGB_BRAM/RGB_BRAM_ooc.xdc

# XDC: bd/design_PLL/design_PLL_ooc.xdc
