# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0.xci
# IP: The module: 'PLL_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0.xci
# IP: The module: 'PLL_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
