# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/BRAM_RGB/ip/BRAM_RGB_blk_mem_gen_R_0/BRAM_RGB_blk_mem_gen_R_0.xci
# IP: The module: 'BRAM_RGB_blk_mem_gen_R_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/BRAM_RGB/ip/BRAM_RGB_blk_mem_gen_R_0/BRAM_RGB_blk_mem_gen_R_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_RGB_blk_mem_gen_R_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/BRAM_RGB/ip/BRAM_RGB_blk_mem_gen_R_0/BRAM_RGB_blk_mem_gen_R_0.xci
# IP: The module: 'BRAM_RGB_blk_mem_gen_R_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/workspace/PYNQ_Z2/project_LCD/project_LCD.srcs/sources_1/bd/BRAM_RGB/ip/BRAM_RGB_blk_mem_gen_R_0/BRAM_RGB_blk_mem_gen_R_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_RGB_blk_mem_gen_R_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
