##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  ÖÜÈÕ 1ÔÂ 6 12:15:58 2019
##  Generated by MIG Version 4.1
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A35T-FTG256
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         0 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J128M16XX-15E
## Data Width: 16
## Time Period: 2500
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################


# PadFunction: IO_L1P_T0_AD4P_35 
set_property IOSTANDARD LVCMOS25 [get_ports {init_calib_complete}]
set_property PACKAGE_PIN B7 [get_ports {init_calib_complete}]

# PadFunction: IO_L2P_T0_AD12P_35 
set_property IOSTANDARD LVCMOS25 [get_ports {tg_compare_error}]
set_property PACKAGE_PIN B6 [get_ports {tg_compare_error}]


set_property INTERNAL_VREF  0.750 [get_iobanks 15]