# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PS/PS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS || ORIG_REF_NAME==PS} -quiet] -quiet

# IP: bd/PS/ip/PS_processing_system7_0_0/PS_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PS_processing_system7_0_0 || ORIG_REF_NAME==PS_processing_system7_0_0} -quiet] -quiet

# XDC: bd/PS/PS_ooc.xdc
