# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/display_test.xdc

# Block Designs: bd/blkmem/blkmem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkmem || ORIG_REF_NAME==blkmem} -quiet] -quiet

# IP: bd/blkmem/ip/blkmem_blk_mem_gen_0_0/blkmem_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blkmem_blk_mem_gen_0_0 || ORIG_REF_NAME==blkmem_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/clkwiz/clkwiz.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clkwiz || ORIG_REF_NAME==clkwiz} -quiet] -quiet

# IP: bd/clkwiz/ip/clkwiz_clk_wiz_0_0/clkwiz_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clkwiz_clk_wiz_0_0 || ORIG_REF_NAME==clkwiz_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/blkmem/blkmem_ooc.xdc

# XDC: bd/clkwiz/clkwiz_ooc.xdc
