# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx/workspace/PYNQ_Z2/DisplayTest/DisplayTest.srcs/sources_1/bd/ps/ip/ps_processing_system7_0_0/ps_processing_system7_0_0.xci
# IP: The module: 'ps_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/workspace/PYNQ_Z2/DisplayTest/DisplayTest.srcs/sources_1/bd/ps/ip/ps_processing_system7_0_0/ps_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Xilinx/workspace/PYNQ_Z2/DisplayTest/DisplayTest.srcs/sources_1/bd/ps/ip/ps_processing_system7_0_0/ps_processing_system7_0_0.xci
# IP: The module: 'ps_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/workspace/PYNQ_Z2/DisplayTest/DisplayTest.srcs/sources_1/bd/ps/ip/ps_processing_system7_0_0/ps_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
