# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/project_LCD.xdc

# Block Designs: bd/BRAM_RGB/BRAM_RGB.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_RGB || ORIG_REF_NAME==BRAM_RGB} -quiet] -quiet

# IP: bd/BRAM_RGB/ip/BRAM_RGB_blk_mem_gen_0_0/BRAM_RGB_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_RGB_blk_mem_gen_0_0 || ORIG_REF_NAME==BRAM_RGB_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/BRAM_RGB/ip/BRAM_RGB_blk_mem_gen_R_0/BRAM_RGB_blk_mem_gen_R_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_RGB_blk_mem_gen_R_0 || ORIG_REF_NAME==BRAM_RGB_blk_mem_gen_R_0} -quiet] -quiet

# IP: bd/BRAM_RGB/ip/BRAM_RGB_blk_mem_gen_R_1/BRAM_RGB_blk_mem_gen_R_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_RGB_blk_mem_gen_R_1 || ORIG_REF_NAME==BRAM_RGB_blk_mem_gen_R_1} -quiet] -quiet

# Block Designs: bd/PLL/PLL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLL || ORIG_REF_NAME==PLL} -quiet] -quiet

# IP: bd/PLL/ip/PLL_clk_wiz_0_0/PLL_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLL_clk_wiz_0_0 || ORIG_REF_NAME==PLL_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/BRAM_RGB/BRAM_RGB_ooc.xdc

# XDC: bd/PLL/PLL_ooc.xdc
